"""Add password to users table

Revision ID: 857039842dd9
Revises: 2aaa57bd2fa2
Create Date: 2026-06-19 23:51:23.116308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857039842dd9'
down_revision: Union[str, Sequence[str], None] = '2aaa57bd2fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashedPassword', sa.String(length=100),server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashedPassword')
    # ### end Alembic commands ###
