"""Migrate to 1 : N relationship between User and categories

Revision ID: c5b61040233c
Revises: e846c6146a2e
Create Date: 2026-06-20 19:15:57.225583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b61040233c'
down_revision: Union[str, Sequence[str], None] = 'e846c6146a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_categories_xref')
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['name', 'user_id'], schema='public')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='public', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'user_id')
    op.create_table('user_categories_xref',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], name=op.f('user_categories_xref_categories_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_categories_xref_user_id_fkey'))
    )
    # ### end Alembic commands ###
