"""Add balance field

Revision ID: ce1845e19025
Revises: c5b61040233c
Create Date: 2026-06-20 21:20:01.833926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1845e19025'
down_revision: Union[str, Sequence[str], None] = 'c5b61040233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=False, server_default='10000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
