"""add categories and user_categories_xref table

Revision ID: e846c6146a2e
Revises: 6f93f40c6928
Create Date: 2026-06-20 15:47:11.615740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e846c6146a2e'
down_revision: Union[str, Sequence[str], None] = '6f93f40c6928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_categories_id'), 'categories', ['id'], unique=False, schema='public')
    op.create_table('user_categories_xref',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['public.categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_categories_xref', schema='public')
    op.drop_index(op.f('ix_public_categories_id'), table_name='categories', schema='public')
    op.drop_table('categories', schema='public')
    # ### end Alembic commands ###
